### PR TITLE
Fix compiler warnings

### LINKED ISSUE #41: Fix compiler warnings

### LINKED ISSUE #52: Split KafkaW into file for each class
similar to [this PR on the filewriter](https://github.com/ess-dmsc/kafka-to-nexus/pull/128)

split the producer, consumer, pollstatus etc into separate files in a `KafkaW` directory.

### PR DESCRIPTION
**Pull request by dominikwerder**
Fixes compiler warnings.
Updates KafkaW.

Closes #41 
Closes #52

### CODE REVIEW

**Comment by dominikwerder** [comment]
Not ready yet, Windows build needs a bit more love.

**Comment by matthew-d-jones** [comment]
@dominikwerder Let me know if you need any help with the Windows build. I've got a Windows box on my desk.

**Comment by matthew-d-jones** [comment]
@dominikwerder It would be great if we could also get rid of compiler warnings from the dependencies, so that we know any that are present are fixable by us. This should be possible by using `SYSTEM` keyword when using `target_include_directories` on external dependencies. For example line 91 of `src/CMakeLists.txt`.

File: src/Kafka.cxx [hunk 1]
```diff
@@ -76,16 +77,16 @@ void InstanceSet::log_stats() {
...
+        p->outputQueueLength());
   }
 }
 
-std::vector<KafkaW::Producer::Stats> InstanceSet::stats_all() {
-  std::vector<KafkaW::Producer::Stats> ret;
+std::vector<KafkaW::ProducerStats> InstanceSet::stats_all() {
+  std::vector<KafkaW::ProducerStats> ret;
   std::unique_lock<std::mutex> lock(mx_producers_by_host);
   for (auto m : producers_by_host) {
```
Comment (rerpha) [inline src/Kafka.cxx]: could this be done by const reference instead of copying?

File: src/Kafka.cxx [hunk 2]
```diff
@@ -76,16 +77,16 @@ void InstanceSet::log_stats() {
...
```
[the remark this answers is not in the document]
Comment (dominikwerder) [reply src/Kafka.cxx]: Sure, it can, but that trades readability for virtually no performance gain on a non-critical path. I vote against.

[the remark this answers is not in the document]
Comment (matthew-d-jones) [reply src/Kafka.cxx]: I would define code with poor readability as being code where it is not obvious what it is doing and thus requires longer to read and understand. For example where one has to look at a much wider context to understand what a single line is doing.
It doesn't take any longer to read and understand `const &`, in fact it has the advantage that it gives the information that a copy is not required and enforces that the variable is not modified unless someone makes the conscious decision to remove `const`.

LLVM guidelines also encourage use of `&` with `auto` wherever a copy is not required: https://llvm.org/docs/CodingStandards.html#beware-unnecessary-copies-with-auto

[the remark this answers is not in the document]
Comment (dominikwerder) [reply src/Kafka.cxx]: Out of curiosity:

> in fact it has the advantage that it gives the information that a copy is not required

And exactly what advantage is that, except if concerned with performance? And, just by looking at that line, you will still never be sure if there is no copy further downstream.

> and enforces that the variable is not modified

That's not an advantage of the `const &` approach, but a necessity.

The only advantage I see remains the performance, which is legit of course. This is also the only advantage that the LLVM style mentions.

Anyways, LLVM rules, so changing this.

File: src/KafkaW/Producer.cxx [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+      "IID: {}  broker: {}  rd_kafka_poll()  served: {}  outq_len: {}", id,
+      ProducerBrokerSettings.Address, events_handled, outputQueueLength());
+  if (log_level >= 8) {
+    rd_kafka_dump(stdout, RdKafkaPtr);
+  }
+  Stats.poll_served += events_handled;
+  Stats.out_queue = outputQueueLength();
+}
+
+void Producer::pollWhileOutputQueueFilled() {
```
Comment (matthew-d-jones) [inline src/KafkaW/Producer.cxx]: I don't think this is ever used

File: src/KafkaW/Producer.cxx [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+  while (outputQueueLength() > 0) {
+    Stats.poll_served +=
+        rd_kafka_poll(RdKafkaPtr, ProducerBrokerSettings.PollTimeoutMS);
+  }
+}
+
+rd_kafka_t *Producer::getRdKafkaPtr() const { return RdKafkaPtr; }
+
+uint64_t Producer::outputQueueLength() { return rd_kafka_outq_len(RdKafkaPtr); }
```
Comment (matthew-d-jones) [inline src/KafkaW/Producer.cxx]: Make cast explicit if intentional

File: src/KafkaW/Producer.h [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+  static void cb_log(rd_kafka_t const *rk, int level, char const *fac,
+                     char const *buf);
+  static void cb_throttle(rd_kafka_t *rk, char const *broker_name,
+                          int32_t broker_id, int throttle_time_ms,
+                          void *opaque);
+  rd_kafka_t *getRdKafkaPtr() const;
+  std::function<void(rd_kafka_message_t const *msg)> on_delivery_ok;
+  std::function<void(rd_kafka_message_t const *msg)> on_delivery_failed;
+  std::function<void(Producer *, rd_kafka_resp_err_t)> on_error;
+  // Currently it's nice to have acces to these two for statistics:
```
Comment (matthew-d-jones) [inline src/KafkaW/Producer.h]: Typo "access"

File: src/KafkaW/ProducerTopic.cxx [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+  std::swap(RdKafkaTopic, x.RdKafkaTopic);
+  std::swap(Name, x.Name);
+  std::swap(DoCopyMsg, x.DoCopyMsg);
+}
+
+struct Msg_ : public Producer::Msg {
+  vector<uchar> v;
+  void finalize() {
+    data = v.data();
+    size = v.size();
```
Comment (matthew-d-jones) [inline src/KafkaW/ProducerTopic.cxx]: Make cast explicit if intentional

File: src/KafkaW/ProducerTopic.cxx [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+  }
+};
+
+int ProducerTopic::produce(uchar *MsgData, size_t MsgSize, bool PrintError) {
```
Comment (matthew-d-jones) [inline src/KafkaW/ProducerTopic.cxx]: `PrintError` isn't used

File: src/KafkaW/ProducerTopic.cxx [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+  x = rd_kafka_produce(RdKafkaTopic, partition, msgflags, Msg->data, Msg->size,
+                       key, key_len, Msg.get());
+
+  auto &s = Producer_->Stats;
+  if (x != 0) {
+    auto err = rd_kafka_last_error();
+    bool print_err = true;
+    if (err == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
+      ++s.local_queue_full;
+      if (print_err) {
```
Comment (matthew-d-jones) [inline src/KafkaW/ProducerTopic.cxx]: Remove `print_err` and `if` statements?

File: src/KafkaW/TopicSettings.cxx [hunk 9]
```diff
@@ -0,0 +1,31 @@
+#include "TopicSettings.h"
+#include <vector>
+
+namespace KafkaW {
+
+TopicSettings::TopicSettings() {}
```
Comment (matthew-d-jones) [inline src/KafkaW/TopicSettings.cxx]: `= default`

File: src/tests/remote.cxx [hunk 10]
```diff
@@ -309,25 +309,27 @@ TEST_F(Remote_T, simple_f142_via_config_message) {
...
-            bopt.conf_strings["group.id"] =
+            KafkaW::BrokerSettings BrokerSettings;
+            BrokerSettings.ConfigurationStrings["group.id"] =
                 fmt::format("forwarder-tests-{}--{}", getpid(), cid);
-            bopt.conf_ints["receive.message.max.bytes"] = 25100100;
-            // bopt.conf_ints["session.timeout.ms"] = 1000;
-            bopt.address = Tests::main_opt->brokers_as_comma_list();
+            BrokerSettings.ConfigurationIntegers["receive.message.max.bytes"] =
+                25100100;
+            // BrokerSettings.ConfigurationIntegers["session.timeout.ms"] =
```
Comment (matthew-d-jones) [inline src/tests/remote.cxx]: Should the comment just be removed? What is it here for?

**Comment by dominikwerder** [comment]
@matthew-d-jones yes, they're supposed to be the same, and I actually working on separating that out :-)
